# Generated by Django 6.0.7 on 2026-07-30 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=200)),
                ('project_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('meeting_type', models.CharField(choices=[('in_person', 'In Person'), ('virtual', 'Virtual')], default='virtual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('architect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architect_consultations', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_consultations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
